import { useMemo, useState } from 'react';
import { civilDatesForView, buildPrayerCalendarDay, hijriCalendarLabel, utcCivilDate, type PrayerCalendarView } from '../domain/prayerCalendar';
import { formatLocalTime, localeTag } from '../i18n/i18n';
import { getApplicationStorage } from '../platform/applicationStorage';
import { defaultPersistedSettings, loadPersistedSettings } from '../platform/settingsStorage';
const views:PrayerCalendarView[]=['daily','weekly','monthly','yearly'];
const prayerNames={fajr:'Fajr',sunrise:'Sunrise',dhuhr:'Dhuhr',asr:'Asr',maghrib:'Maghrib',isha:"Isha'"} as const;
function settings(){try{return loadPersistedSettings(getApplicationStorage());}catch{return defaultPersistedSettings;}}
function todayCivil(){const n=new Date();return utcCivilDate(n.getFullYear(),n.getMonth()+1,n.getDate());}
export function PrayerCalendarScreen(){const config=useMemo(settings,[]);const[view,setView]=useState<PrayerCalendarView>('monthly');const[anchor,setAnchor]=useState(todayCivil);const locale=config.locale;const move=(delta:number)=>setAnchor(d=>{const y=d.getUTCFullYear(),m=d.getUTCMonth();if(view==='yearly')return utcCivilDate(y+delta,m+1,1);if(view==='monthly')return utcCivilDate(y,m+1+delta,1);return new Date(d.getTime()+delta*(view==='weekly'?7:1)*86_400_000);});const dates=useMemo(()=>view==='yearly'?[]:civilDatesForView(anchor,view),[anchor,view]);const rows=useMemo(()=>dates.map(d=>buildPrayerCalendarDay(d,config)),[dates,config]);const title=view==='yearly'?String(anchor.getUTCFullYear()):view==='monthly'?new Intl.DateTimeFormat(localeTag(locale),{timeZone:'UTC',month:'long',year:'numeric'}).format(anchor):new Intl.DateTimeFormat(localeTag(locale),{timeZone:'UTC',day:'numeric',month:'short',year:'numeric'}).format(anchor);
return <main className="prayer-calendar" data-calendar-view={view}><header className="prayer-calendar__header"><p>Prayer Calendar</p><h1>{title}</h1><span>{config.location?.timeZone??'Set a location to calculate prayer times'}</span></header><div className="prayer-calendar__views" role="tablist" aria-label="Calendar view">{views.map(v=><button key={v} role="tab" aria-selected={view===v} onClick={()=>setView(v)}>{v[0].toUpperCase()+v.slice(1)}</button>)}</div><div className="prayer-calendar__pager"><button onClick={()=>move(-1)} aria-label="Previous period">‹</button><button onClick={()=>setAnchor(todayCivil())}>Current</button><button onClick={()=>move(1)} aria-label="Next period">›</button></div>{view==='yearly'?<YearView year={anchor.getUTCFullYear()} correction={config.hijriCorrectionDays} onMonth={m=>{setAnchor(utcCivilDate(anchor.getUTCFullYear(),m,1));setView('monthly');}}/>:<section className="prayer-calendar__table-wrap"><table><thead><tr><th>Date</th>{Object.values(prayerNames).map(n=><th key={n}>{n}</th>)}</tr></thead><tbody>{rows.map((row,i)=>{const d=dates[i]!;return <tr key={d.toISOString()}><th><strong>{new Intl.DateTimeFormat(localeTag(locale),{timeZone:'UTC',weekday:'short',day:'numeric',month:view==='monthly'?'short':undefined}).format(d)}</strong><small>{row?.hijri.label??hijriCalendarLabel(d,config.hijriCorrectionDays).label}</small></th>{Object.keys(prayerNames).map(name=>{const prayer=row?.prayers.find(p=>p.name===name);return <td key={name}>{prayer?.localMinutes==null?'—':formatLocalTime(prayer.localMinutes,locale,config.timeFormat)}</td>})}</tr>})}</tbody></table></section>}<p className="prayer-calendar__note">Hijri dates use Umm al-Qura with your configured Hijri correction. Prayer times use the same location, calculation method, madhhab/Asr convention and adjustments as SalahOS.</p></main>}
function YearView({year,correction,onMonth}:{year:number;correction:number;onMonth:(month:number)=>void}){return <section className="prayer-calendar__year" aria-label={`${year} calendar`}>{Array.from({length:12},(_,i)=>{const date=utcCivilDate(year,i+1,1),start=hijriCalendarLabel(date,correction),end=hijriCalendarLabel(utcCivilDate(year,i+2,0),correction);return <button key={i} onClick={()=>onMonth(i+1)}><span>{i+1}</span><strong>{new Intl.DateTimeFormat('en-AU',{timeZone:'UTC',month:'short'}).format(date).toUpperCase()}</strong><small>{new Intl.DateTimeFormat('en-AU',{timeZone:'UTC',month:'long'}).format(date)}</small><em>{start.monthName}{start.year!==end.year||start.month!==end.month?` – ${end.monthName}`:''}</em><small>{start.year===end.year?`${start.year} AH`:`${start.year}–${end.year} AH`}</small></button>})}</section>}
